### ISSUE TITLE
Index page '/prolog' is not available offline

### ISSUE THREAD

**Issue by razetime** [triska/the-power-of-prolog#38] opened 2022-09-04 05:39 UTC
In the [Reading This Book](https://github.com/triska/the-power-of-prolog#reading-this-book) section it is mentioned to direct the browser to `http://localhost:6012/prolog`. However, the server just redirects to the online version of the page. It would make sense to have it available, or use a different example i.e. `prolog/introduction` works fine.

**Comment by triska** [comment] 2022-09-04 09:52
Could you please try it with the latest development version of Scryer Prolog, available from the `rebis-dev` branch on github? This version contains several corrections and improvements, and it works offline as intended, at least on the machine where I just tried it, also for the index page!

**Comment by razetime** [comment] 2022-09-04 10:53
after checking out `rebis-dev` and rebuilding, this is the output I get:
```
$ spl -v
"v0.9.0-231-gdfebef2e"
$ cd ~/Documents/books/the-power-of-prolog/
$ spl -g "server(6012)" server.pl
Warning: initialization failed for "server(6012)"
?-
```

**Comment by razetime** [comment] 2022-09-04 11:06
oh, sorry about the false alarm. It seems 6012 was occupied by an older process. It works fine now. Only thing I'd ask is to add a line saying "use the `rebis-dev` build for best results".

**Comment by triska** [comment] 2022-09-04 14:32
The `master` branch should work just as well! I recommend the `rebis-dev` branch only currently, since it has a few improvements on top of the `master` branch, and it will be out of date again as soon as it is merged into `master`. The `rebis-dev` branch is used for particularly intrusive changes in Scryer&nbsp;Prolog, it was only active 3 times so far (for better meta-predicates 2 years ago, a better heap representation earlier this year, and currently for partial compilation of meta-goals).

**Closed** 2022-09-06 03:27 UTC
